social_auth_dropbox.settings:
  type: config_object
  label: 'Social Auth Dropbox settings'
  mapping:
    app_key:
      type: string
      label: 'App Key'
    app_secret:
      type: string
      label: 'App Secret'
    endpoints:
      type: string
      label: 'API Endpoints to be requested'
